service: alien-vault-reputation
provider:
  name: aws
  runtime: python2.7
  timeout: ${file(./serverless.env.yml):${opt:stage}.TIME_OUT}
  iamRoleStatements:
    - Effect: Allow
      Action:
      - "logs:CreateLogGroup"
      Resource: "arn:aws:logs:*:*:*"
    - Effect: Allow
      Action:
      - "logs:CreateLogStream"
      Resource: "arn:aws:logs:*:*:*"
    - Effect: Allow
      Action:
      - "logs:PutLogEvents"
      Resource: "arn:aws:logs:*:*:*"
    - Effect: Allow
      Action:
      - "dynamodb:PutItem"
      Resource: "arn:aws:dynamodb:*:*:*"
    - Effect: Allow
      Action:
      - "dynamodb:BatchWriteItem"
      Resource: "arn:aws:dynamodb:*:*:*"
  environment:
    REGION: ${opt:region}
    IP_REPUTATION_TABLE: ${file(./serverless.env.yml):${opt:stage}.IP_REPUTATION_TABLE}
    SOURCE_URL: ${file(./serverless.env.yml):${opt:stage}.SOURCE_URL}
functions:
  SampleCloudTrail:
    handler: handler.source_lists
    description: Alien vault reputation for ${file(./serverless.env.yml):${opt:stage}.ENVIRONMENT} environment
    name: alien_vault_${file(./serverless.env.yml):${opt:stage}.ENVIRONMENT}
    memorySize: 2048
    events:
     - schedule: cron(0 18 ? * MON-FRI *)
resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: dl-extnernal-alien-vault-reputation
        AttributeDefinitions:
          - AttributeName: IP
            AttributeType: S
        KeySchema:
          - AttributeName: IP
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TimeToLiveSpecification:
          AttributeName: IP
          Enabled: True
