service: s3-bucket-access
provider:
  name: aws
  runtime: python2.7
  timeout: ${file(./serverless.env.yml):${opt:stage}.TIME_OUT}
  iamRoleStatements:
    - Effect: Allow
      Action:
      - "logs:CreateLogGroup"
      Resource: "arn:aws:logs:*:*:*"
    - Effect: Allow
      Action:
      - "logs:CreateLogStream"
      Resource: "arn:aws:logs:*:*:*"
    - Effect: Allow
      Action:
      - "logs:PutLogEvents"
      Resource: "arn:aws:logs:*:*:*"
    - Effect: Allow
      Action:
      - "sqs:SendMessage"
      Resource: "arn:aws:sqs:${file(./serverless.env.yml):${opt:stage}.REGION}:${opt:ACCOUNT_ID}:${file(./serverless.env.yml):${opt:stage}.ANALYTICS_QUEUE_NAME}"

    - Effect: Allow
      Action:
      - "sqs:SendMessage"
      Resource: "arn:aws:sqs:${file(./serverless.env.yml):${opt:stage}.REGION}:${opt:ACCOUNT_ID}:${file(./serverless.env.yml):${opt:stage}.DATA_LAKE_SERIES_QUEUE}"

  environment:
    REGION: ${opt:region}
    ANALYTICS_QUEUE_NAME: https://sqs.${opt:region}.amazonaws.com/${opt:ACCOUNT_ID}/${file(./serverless.env.yml):${opt:stage}.ANALYTICS_QUEUE_NAME}
    DATA_LAKE_SERIES_QUEUE: https://sqs.${opt:region}.amazonaws.com/${opt:ACCOUNT_ID}/${file(./serverless.env.yml):${opt:stage}.DATA_LAKE_SERIES_QUEUE}
functions:
  SampleS3ACCESS:
    handler: handler.create
    description: S3 bucket access for ${file(./serverless.env.yml):${opt:stage}.ENVIRONMENT} environment
    name: s3_bucket_${file(./serverless.env.yml):${opt:stage}.ENVIRONMENT}
    events:
     # - sns: arn:aws:sns:us-east-1:659153740712:legacy_default_vpc_flow_logs
    tags:
      Role: Security
